### ISSUE TITLE
DateInput/fuseau horaire et Select/Placeholder

### ISSUE THREAD

**Issue by PuNiiiX** [AxaGuilDEv/react-toolkit#102]
Bonjour,

Comment puis-je régler le problème du fuseau horaire avec le DateInput ? 
 
```
  <DateInput
      label="Date de prise d'effet du nouveau contrat *"
      locale="fr-fr"
      value={pricing.effectiveDateBloc.effectiveDate.value}
      message={pricing.errors.effectiveDate}
      viewValue={pricing.effectiveDateBloc.effectiveDate.viewValue}
      classNameContainerLabel="col-md-4"
      classNameContainerInput="col-md-7"
      onChange={effectiveDateChanged}
      name="effectiveDate"
      helpMessage="jj/mm/aaaa"
      fixedHeight
      showMonthDropdown
      showYearDropdown
      readOnly={false}
      autoFocus={false}
      todayButton={"Aujourd'hui"}
      popperPlacement="right-start"
      yearDropdownItemNumber={6}
    />
```
 
 Si l'utilisateur choisi 01/05/2019, on a comme valeur  : 2019-04-30T22:00:00Z
 
Ensuite,
 
J’ai également une liste déroulante, qui doit garder comme valeur, une valeur vide, car le choix utilisateur peut être annulé et dans ce cas là il doit choisir la ligne vide. (donc impossible d'utiliser le placeholder pour cela)
 
Hors quand on met Select, on est obligé d’avoir un placeHolder :
 
         <Select
                    name="rabais"
                    id="clauses"
                    value={rabais}
                    onChange={handleRabais}
                    options={listOfRabais.map(ca => ({
                      value: ca.code,
                      label: ca.commercialActionLabel,
                    }))}
                    placeholder=" - Sélectionner - "
                  />
 
 
Du coup je me retrouve avec des erreurs dans la console, car j’ai 2 valeurs de mon select à vide. Une fois une valeur choisi, le placeholder s’en va et je n’ai plus l’erreur, mais je ne voudrais plus avoir de placeholder. j’ai essayé de l’enlever, le mettre à vide, etc… mais il est toujours présent.

Merci beaucoup,

**Comment by guillaumechervetaxa** [comment]
Quel Pseudo Aurélien !

Pour la date, il faut importer les locals dont tu as besoin. c'est écrit dans le readme du composant date dans storybook 
 https://axaguildev.github.io/react-toolkit/v1.1.2/storybook/index.html?selectedKind=Form.Input.Date&selectedStory=DateInput&full=0&addons=1&stories=1&panelRight=1&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
ici aussi 
https://facebook.github.io/create-react-app/docs/troubleshooting#momentjs-locales-are-missing

Sur le storybook avec l'import de la langue fr-fr ça fonctione:
![image](https://user-images.githubusercontent.com/43414465/53798256-26039c00-3f38-11e9-8490-1b426ef4f538.png)


Pour le select, je pense que le SelectBase répond a ton besoin, ce composant est sans état et ne gère pas la règle d'ergonomie AXA avec le - Séléctionner - 
https://axaguildev.github.io/react-toolkit/v1.1.2/storybook/index.html?selectedKind=Form.Input.Select&selectedStory=SelectBase&full=0&addons=1&stories=1&panelRight=1&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

Es-ce que ça répond bien a t'es question mec?

**Comment by arnaudforaison** [comment]
@PuNiiiX cette issue peut être fermée ?
