### ISSUE TITLE
PassInput borders are not red on error

### ISSUE THREAD

**Issue by bernard-arnaud** [AxaGuilDEv/react-toolkit#105]
### Issue and Steps to Reproduce

Add a PassInput component and put an error message in it

#### Screenshots
![image](https://user-images.githubusercontent.com/47565500/54127466-230e1d00-440a-11e9-94b2-466352b64886.png)

#### Expected

Red borders (like the Email TextInput in the screenshot)

#### Actual

Black borders

**Comment by arnaudforaison** [comment]
A component pass input exist
