### ISSUE TITLE
TabsStateless doesn't have a key prop

### ISSUE THREAD

**Issue by bernard-arnaud** [AxaGuilDEv/react-toolkit#107]
#### Screenshots
![image](https://user-images.githubusercontent.com/47565500/54216224-8d49bf00-44e9-11e9-81b7-e50e0c511dc4.png)

#### Expected
![image](https://user-images.githubusercontent.com/47565500/54217764-8bcdc600-44ec-11e9-9583-790760059917.png)

Expected key prop to be passed down to Tab component

#### Actual

TabsStateless doesn't have a key prop

#### Additional Details

- Installed packages

**Comment by arnaudforaison** [comment]
Do you have this issue @bernard-arnaud ?
