### ISSUE TITLE
MultiSelect input emptying

### ISSUE THREAD

**Issue by Gparquet** [AxaGuilDEv/react-toolkit#109]
### Issue and Steps to Reproduce

The problem occurs when the field is empty.

If you want to reset the field, it stores the last value added. It seems to me that this behavior only occurs when the list contains more than one element

I tried passing it in the properties value = "" and or values = [], I get the same result.

1°) You can reproduce the problem by inserting more than one item into the list.

2°) Select a value

3°) Then pass the property value = ""

#### Versions
1.1.2 
#### Additional Details

- Installed packages

**Comment by oussamahamdaoui** [comment]
+1
