### ISSUE TITLE
rewrite stories with standard syntax

### ISSUE THREAD

**Issue by samuel-gomez-axa** [AxaGuilDEv/react-toolkit#111]
### Issue and Steps to Reproduce

For futures updates, we should write the stories on standard format and no longer using the custom addon storybook (addStories)

#### Versions
1.2.0

#### Additional Details

- Installed packages

**Comment by guillaumechervetaxa** [comment]
I don't understand d what you mean Samuel. Is it not already the case? There is just a small wrapper in order to avoid Duplication of code which is a good practice I think.

**Comment by samuel-gomez-axa** [comment]
When I added the **new design system**, I had **conflicts** with the parent packages.
So I tried to clean the **main package**.json and put the dependencies on each packages.
When I tried to **update the storybook** (5.0.3), it could **not see the stories** anymore.
I tested with a simple simple story like this :

```
import React from 'react';
import { storiesOf } from '@storybook/react';

storiesOf('Test', module)
  .add('with text', () => (
    <p>Hello Test component</p>
  ));  
```

And it works.

I think the new version of storybook changed parsing code method. 
So i suggest to keep the official synthax without wrapper.

**Comment by guillaumechervetaxa** [comment]
I pretty sure that the problem is somewhere else Samuel. May be a not compatible version of a something and somewhere.
