### ISSUE TITLE
[MenuTitleWrapper] Menu not aligned with UX recommandations

### ISSUE THREAD

**Issue by a-bastin** [AxaGuilDEv/react-toolkit#116]
#### Versions

Latest version (v1.2.0)

#### Screenshots

From the story book :

![image](https://user-images.githubusercontent.com/1699518/54767578-b7903080-4bfd-11e9-9fdd-f5964a606727.png)

#### Expected

<img width="877" alt="headertoolkit" src="https://user-images.githubusercontent.com/1699518/54767600-c5de4c80-4bfd-11e9-9659-f8dd5aa65601.PNG">

#### Additional Details

The menu names shouldn't be in bold and not underlined

- Installed packages

**Comment by arnaudforaison** [comment]
Do you think it's still current ?

**Comment by Yoda6** [comment]
According to the design system (https://axaguildev.github.io/react-toolkit/latest/design/molecules/navigation/) yes it's still current
