### ISSUE TITLE
[LinkWithAction] add new component like that

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-toolkit#145]
![image](https://user-images.githubusercontent.com/43414465/55955681-51c62000-5c62-11e9-8676-b3b47e9631b2.png)
![image](https://user-images.githubusercontent.com/43414465/55955769-8fc34400-5c62-11e9-8dc3-ae912f22d8ee.png)
![image](https://user-images.githubusercontent.com/43414465/56749490-1b1ff780-6782-11e9-8b6d-c36f35fa227f.png)

Compoent should be disablable

**Comment by arnaudforaison** [comment]
More details please.
Still current ?
