### ISSUE TITLE
Popover doesn't work

### ISSUE THREAD

**Issue by QuentinBarroin** [AxaGuilDEv/react-toolkit#17]
### Issue and Steps to Reproduce
The current component doesn't work.
We have this error : 
**### Element type is invalid: expected a string (for built-in components) or a class/function but got: undefined.
You likely forgot to export your component from the file it's defined in, or you have mixed up default and name imports.**

**_Check the render method of 'AnimatedPopover'_**

The import is the following :
`import Popover, { PopoverBase } from '@axa-fr/react-toolkit-popover';`

The use of case is the following :
 ```
<PopoverBase
          className="af-popover__container af-popover__infos"
          isOpen={isOpen}
          placement="top"
          onToggle={event => {
            onToggle(isOpen);
            setTimeout(onToggle, 3000);
          }}
        >
          <Popover.Pop>
            <h3>Infos contrat</h3>
            <dl>
              <dt>Nom : </dt>
              <dd>{studyName}</dd>
            </dl>
            <dl>
              <dt>Collège : </dt>
              <dd>{studyCollege}</dd>
            </dl>
            <dl>
              <dt>Dernière modification : </dt>
              <dd>
                <span>{studyLastupdateDate}</span>
                <a
                  id="studyLastSave"
                  className="link-lastsave link-lastsave__blue"
                  onClick={() => setPopinLastSaveDisplay(true)}
                >
                  <Icons icon="reset" />
                  <span className="af-link">
                    Retour à la dernière sauvegarde
                  </span>
                </a>
              </dd>
            </dl>
            <dl>
              <dt>Saisie : </dt>
              <dd>{studyStatus}</dd>
            </dl>
          </Popover.Pop>
          <Popover.Over>
            <Infos
              infos={[
                { word: 'Nom :', definition: studyName },
                { word: 'Collège :', definition: studyCollege },
                { word: 'Saisie :', definition: studyStatus },
                {
                  word: 'Dernière modification :',
                  definition: studyLastupdateDate,
                },
              ]}
            />
          </Popover.Over>
        </PopoverBase>
```

### Versions
"@axa-fr/react-toolkit-core": "^1.0.0",
"@axa-fr/react-toolkit-all": "1.0.0",

### Screenshots
![bug-toolkit](https://user-images.githubusercontent.com/3921451/50273971-55783180-043c-11e9-8cb7-0406f83d1f7c.PNG)

#### Expected
By following this link below, you can see the expected result.
https://axaguildev.github.io/react-toolkit/storybook/v1.0.0/index.html?knob-classModifier=&knob-className=&knob-placement=right&knob-mode=hover&knob-isOpen=true&selectedKind=Popover&selectedStory=PopoverBase&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

#### Actual
The component doesn't work.

- Installed packages:
...
"@axa-fr/react-toolkit-core": "^1.0.0",
"@axa-fr/react-toolkit-all": "1.0.0",
...

**Comment by samuel-gomez-axa** [comment]
Hi @barry-thierno 
Before close this issue, i find a bug on click event Popover.
You can see it on browser console here : https://axaguildev.github.io/react-toolkit/latest/storybook/?path=/story/popover--popoverbase
<img width="1000" alt="Capture d’écran 2019-04-19 à 21 20 09" src="https://user-images.githubusercontent.com/43414022/56440214-12927180-62e9-11e9-9640-1e0cec049faf.png">

**Comment by vincent-ducrocq-axa** [comment]
Hello @samuel-gomez-axa, @QuentinBarroin 
I try to use popover but I have error with click mode.
Nothing is open and I have this errors on console :
![image](https://user-images.githubusercontent.com/50108579/56899859-cb4c7380-6a94-11e9-8f8e-ec8af2cb52de.png)

First error is on page load
Second error is on click

In hover mode, everything is OK

**Comment by guillaumechervetaxa** [comment]
This bug was fixed
