### ISSUE TITLE
[Badge] add possibility to set disabled

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-toolkit#179]
![image](https://user-images.githubusercontent.com/43414465/56800139-a220ae80-681a-11e9-9f47-d5dd35e36036.png)

![image](https://user-images.githubusercontent.com/43414465/56801496-d9448f00-681d-11e9-8c88-b383d8f273af.png)

**Comment by djaumes** [comment]
If it makes sense in the user experience, yes.
