### ISSUE TITLE
[Bug] Higlight button click

### ISSUE THREAD

**Issue by MariBoy7** [AxaGuilDEv/react-toolkit#216]
Highlight au clic alors qu'il derait être qu'au tab. 

<img width="308" alt="btnhighlihgt" src="https://user-images.githubusercontent.com/50369822/57304534-ce241580-70df-11e9-89c6-e37f8e16b898.PNG">

**Comment by elyaB** [comment]
Chez moi ça s'highlight bien au tab. Quel est le nom du composant ?

**Comment by MariBoy7** [comment]
Classification : AXA FR Interne

Bonjour,

Oui ça highlight bien au tab mais ça highlight aussi au clic. Il faudrait supprimer le highlight au clic sur les boutons.

De : Elya Bernard <notifications@github.com>
Envoyé : lundi 13 mai 2019 14:49
À : AxaGuilDEv/react-toolkit <react-toolkit@noreply.github.com>
Cc : BOY Mari <mari.boy@axa.fr>; Author <author@noreply.github.com>
Objet : [EXTERNAL] Re: [AxaGuilDEv/react-toolkit] [Bug] Higlight button click (#216)


Chez moi ça s'highlight bien au tab. Quel est le nom du composant ?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AxaGuilDEv_react-2Dtoolkit_issues_216-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAMAJKHXCHXWFY4OZUSYCU4LPVFPS7A5CNFSM4HLJBHWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVIGNDI-23issuecomment-2D491808397&d=DwMFaQ&c=Z96x8jGkxccf5DH9xuHxeg&r=vIg2BC6_Tn2ls1PGyqDIiA&m=gClIz_0La0LZe8RE1fFIV85JYIcGkkTx23GBtuNve6I&s=oK-ZVtCV_RoIowz6u0VpYjNlRdehSEWcCZU6BFoBniU&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMAJKHTIBMI7IDXS6LCSYXLPVFPS7ANCNFSM4HLJBHWA&d=DwMFaQ&c=Z96x8jGkxccf5DH9xuHxeg&r=vIg2BC6_Tn2ls1PGyqDIiA&m=gClIz_0La0LZe8RE1fFIV85JYIcGkkTx23GBtuNve6I&s=kpOGEAbMWXHdF3vEQJeKo4yDG9_1TVm0nlf-prl9oco&e=>.


Ce message a été classifié par mari.boy@axa.fr le 14/05/2019 09:39

----------------------------------------------------------------------
Ce message est confidentiel. Son contenu ne represente en aucun cas un 
engagement de la part de AXA France sous reserve de tout accord conclu
par ecrit entre  vous et  AXA  France.  Toute publication, utilisation 
ou diffusion, meme  partielle, doit etre autorisee prealablement. Si 
vous n'etes pas destinataire de ce message, merci d'en avertir 
immediatement l'expediteur. 

This message is confidential. Its contents do not constitute a 
commitment by AXA France except where provided for in a written 
agreement between you and AXA France. Any unauthorised disclosure, use 
or dissemination, either whole or partial, is prohibited. If you are 
not the intended recipient of the message, please notify the sender 
immediately.
----------------------------------------------------------------------

**Comment by arnaudforaison** [comment]
@djaumes / @Xym618 vous en penser quoi ? Highlight ou pas au click ? uniquement au tab ?

**Comment by djaumes** [comment]
On est d’accord que le highlight correspond  à l’état « focus »? Si oui, c’est uniquement au tab, focus et click sont deux états différents.

**Comment by arnaudforaison** [comment]
Est ce que ne pas mettre le focus ne poserais pas un problème d'accessibilité ? Vous en pensez quoi @samuel-gomez et @djaumes 
https://www.w3.org/TR/wai-aria-practices-1.1/#button

**Comment by djaumes** [comment]
Focus au tab, pas au click.

Il faut que le focus reste présent car c'est un élément d'accessibilité moteur.
