### ISSUE TITLE
Recette composant react - Header

### ISSUE THREAD

**Issue by vchartier** [AxaGuilDEv/react-toolkit#311]
####  Retour Composant Header

af-header_title : 22.4px => 22px bold
af-header_subtitle : 17.92 => 22px regular
af-contrat : 14.4px => 16px / textcolor #333333 => #4D4D4D
af-title-bar_title : 24px => 22px
af-nav_link : padding 12.8px 17px => 16px
af-title-bar_subtitle : il n'y pas d'espace particulier entre le bar_title et bar_subtitle seulement un espace "space-bar"

- Installed packages

**Comment by vchartier** [comment]
Retour Composant header 

Paddingtop 16px=>0px
`
<img width="1122" alt="Capture d’écran 2019-07-15 à 14 45 24" src="https://user-images.githubusercontent.com/52313794/61217369-cf8d4200-a70f-11e9-954c-3ab8795e599b.png">
`

**Comment by vchartier** [comment]
Retour Composant header 

Logo size
af.logo_brand 51x51px => 33x33px

**Comment by arnaudforaison** [comment]
Est ce que c'est des corrections ? Cela suit il les préco UX ? @vchartier @samuel-gomez-axa

**Comment by Railk** [comment]
@arnaudforaison oui

**Comment by samuel-gomez-axa** [comment]
Une remarque a été faite sur le logo collé en haut de fenêtre, est-ce une anomalie ? @Railk

**Comment by Railk** [comment]
@samuel-gomez-axa Non il est bien collé sur le toolkit y'a pas de marge au dessus :)

**Comment by arnaudforaison** [comment]
Est ce que 
> af-title-bar_title : 24px => 22px
signifie que la font-size doit être changé ou autre chose ? Car je ne retrouve pas de correspondance sur la taille donnée.

**Comment by Railk** [comment]
je recheck et je te dis

**Comment by arnaudforaison** [comment]
C'est bon @Railk j'ai trouvé. C'était bien la font-size mais dans un breakpoint
