### ISSUE TITLE
Recette Composant React - Footer

### ISSUE THREAD

**Issue by vchartier** [AxaGuilDEv/react-toolkit#318]
### Composant Footer

af.footer padding 9px 0px 4px 23px => 8px 0px
af.footer-content font size 12.96px => 11px

**Comment by vchartier** [comment]
Composant Footer 
af-logo_brand 40x40px => 22x22px

**Comment by arnaudforaison** [comment]
Est ce que c'est des corrections ? Cela suit il les préco UX ? @vchartier @samuel-gomez-axa

**Comment by Railk** [comment]
@arnaudforaison oui
