### ISSUE TITLE
Feature request to migrate moment to dayjs

### ISSUE THREAD

**Issue by hamzahamidi** [AxaGuilDEv/react-toolkit#319]
### Feature request for performance reasons

Replace ```Moment.js``` in with [Day.js](https://github.com/iamkun/dayjs/blob/dev/docs/en/API-reference.md#add-addvalue-number-unit-string)

> Day.js is a minimalist JavaScript library that parses, validates, manipulates, and displays dates and times for modern browsers with a largely Moment.js-compatible API. If you use Moment.js, you already know how to use Day.js.

**Dayjs is only 2kb in minimified version.**

I installed both **momentjs** & **dayjs** & here's the difference in size:

![dayjs-moment-hamzahamidi](https://user-images.githubusercontent.com/22576950/61224925-d623b580-a71f-11e9-8edf-056fd00695e9.gif)

Interesting thread for migration: https://github.com/iamkun/dayjs/issues/529

**Comment by johnmeunier** [comment]
Is this issue deprecated ? We have a debate to migrate to a native implementation

**Comment by samuel-gomez-axa** [comment]
we can use this issue for discuss or create another, we still need to migrate
