### ISSUE TITLE
Recette composant react - Input text

### ISSUE THREAD

**Issue by vchartier** [AxaGuilDEv/react-toolkit#320]
### Composant react - Input text

af-form_input-text padding 9px 19.2px => 0px 20px

af-form_help 
color font 333333 => 777777
Font size 12px => 13px

**Comment by djaumes** [comment]
Test comment

**Comment by arnaudforaison** [comment]
Est ce que c'est des corrections ? Cela suit il les préco UX ? @vchartier @samuel-gomez-axa

**Comment by Railk** [comment]
@arnaudforaison oui les retours de @vchartier sont des retours UX suite à nos évolutions du toolkit de notre côté.

Ces améliorations sont une rationalisation des composants, des améliorations suite à des tests utilisateurs etc ... on va revenir vers vous avec plein d'issues pour tout logger ce que @vchartier  n'avait pas eu encore le temps de faire.

**Comment by xballoy** [comment]
@Railk @vchartier vous dites : af-form_input-text padding 9px 19.2px => 0px 20px, ce n'est pas plutôt 10px 20px ? Sinon ca fait vraiment tout petit 🧐

**Comment by xballoy** [comment]
Si je mets 0px 20px ca fait
<img width="484" alt="Screenshot 2020-10-20 at 12 04 03" src="https://user-images.githubusercontent.com/686305/96571855-6d38cf00-12cc-11eb-98e5-687075893d5e.png">

Par contre si je mets 10px 20px ca fait
<img width="553" alt="Screenshot 2020-10-20 at 12 03 49" src="https://user-images.githubusercontent.com/686305/96571875-75910a00-12cc-11eb-8be1-db2870a957bf.png">

**Comment by djaumes** [comment]
Bonjour @xballoy , je reprends le sujet UX avec Xin Yi Mei (à la place de Railk et @vchartier), je pense qu'il y a effectivement une coquille et qu'il faut partir sur 10px 20px. Je confirme avec vchartier ce midi.

**Comment by Railk** [comment]
hello @xballoy je vérifie mais oui c'est plus 10px 20px

**Comment by xballoy** [comment]
Avec 10px ca fait
![10px](https://user-images.githubusercontent.com/686305/96572217-dddfeb80-12cc-11eb-9d44-dd84ad19598c.png)

Avec 0px
![0px](https://user-images.githubusercontent.com/686305/96572220-de788200-12cc-11eb-9650-539c10c6890e.png)

**Comment by djaumes** [comment]
Par contre l'infobulle m'arrache la rétine haha

**Comment by Railk** [comment]
ça fait partie des tickets à écrire :)

**Comment by arnaudforaison** [comment]
Par contre @Railk j'ai un doute sur le correctif de couleur. Car cette couleur n'existe pas dans la charte

**Comment by xballoy** [comment]
Comme vu par @samuel-gomez-axa dans la charte (https://www.sketch.com/s/2ac5fa1d-6be5-4677-923a-c3e7aff0ac24/a/WjOkQy#Inspector) c'est `#7F7F7F` et pas `#777777`. C'est quoi la bonne valeur ? :)

**Comment by djaumes** [comment]
[$color-gray](https://www.sketch.com/s/73328776-a6d4-47b7-a18b-fbb294f8d790/a/jEywZ0)

**Comment by djaumes** [comment]
En inspectant l'ensemble des couleurs présentes dans le toolkit v3, j'ai relevé des [$couleurs] nommées différemment avec des valeurs hexa en doublon.
