### ISSUE TITLE
ChecboxItem value is incorrect

### ISSUE THREAD

**Issue by johnmeunier** [AxaGuilDEv/react-toolkit#369]
### Issue and Steps to Reproduce

Component : CheckboxItem
This component is not easy to use. 

With the current implementation, the user have to set up the sync of the value.

#### Versions
version: 1.2.12

#### Expected
The correct behavior is to return the new state of the checkbox (checked or not) and not just a value. 

#### Actual

It seems to always return the value attribut. If, like in the doc, you pass a string to the value prop, the event return by the onChange will always contains this string in the value attribut. If you pass a variable, it will return the value of this variable.

**Comment by arnaudforaison** [comment]
I don't understand what you want to do better ?

**Comment by johnmeunier** [comment]
I think we can close this issue. It's more a conception problem than a bug. The debates is always around the stateful et stateless component.
