### ISSUE TITLE
Default modal from the Storybook

### ISSUE THREAD

**Issue by triathletefr23** [AxaGuilDEv/react-toolkit#37]
### Description

Impossible to copy the code of the modal from the Storybook (it's impossible to close it to see the code)

### Issue and Steps to Reproduce

Modal => Boolean => Default

### Screenshots

![image](https://user-images.githubusercontent.com/9766356/51393771-d0666200-1b38-11e9-9c86-516e444b2c9e.png)

**Comment by guillaumechervetaxa** [comment]
It is possible to close the modal insing the knowd panel.
It is the correct behavior.
