### ISSUE TITLE
Nav bar is invisible when using full css import

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-toolkit#38]
### Issue and Steps to Reproduce
Nav bar is invisible when using full css import. 
import '@axa-fr/react-toolkit-all/dist/style/af-components.css';

it works when we use the sass associated to the component 
import '@axa-fr/react-toolkit-layout-header/dist/NavBar/nav.scss';

### Versions
1.02
### Screenshots
![image](https://user-images.githubusercontent.com/43414465/51402845-ef6fee80-1b4e-11e9-9455-7fe3fa4e8c13.png)

**Comment by arnaudforaison** [comment]
After 2 years this issue is still current ?
