### ISSUE TITLE
Help component : Uncaught TypeError: Cannot read property 'contains' of undefined 

### ISSUE THREAD

**Issue by bernard-arnaud** [AxaGuilDEv/react-toolkit#385]
### Issue and Steps to Reproduce

Uncaught TypeError: Cannot read property 'contains' of undefined at HTMLDocument.handleEvent when clicking on the Help component or an input next to it.

#### Versions
2.1.15
#### Additional Details

Can be reproduced in the storybook :
https://axaguildev.github.io/react-toolkit/latest/storybook/index.html?path=/story/form-input-text--textinput

**Comment by guillaumechervetaxa** [comment]
Fixed in previous PR
