### ISSUE TITLE
[Bug] SelectInput reinitilization placeholder

### ISSUE THREAD

**Issue by samuel-gomez-axa** [AxaGuilDEv/react-toolkit#402]
### Issue Description

// French
Lorsque l'état du composant Select change, le placeholder disparait.
J'ai un select qui peut être réinitialisé par un autre champ. 
Donc je voudrais pouvoir remettre le placeholder juste en vidant le champ mais ça ne fonctionne pas car si le champ select a déjà subi au moins un changement le placeholder ne revient plus.
Le champ est en erreur alors que la valeur affichée n'est plus le placeholder.
Dans le fichier Select.js 

// English
When the state of the Select component changes, the placeholder disappears.
I have a select that can be reset by another field.
So I would like to reset the field **with the placeholder** but it's not possible because the select field has already changed
.
**In the Select.js file**

```javascript
onChange(e) {
    const { onChange } = this.props;
    onChange(e);
    this.setState({ hasHandleChangeOnce: true });
  }
  getOptions() {
    const { value, placeholder, options } = this.props;
    const { hasHandleChangeOnce } = this.state;

    // Here, the condition to display the placeholder
    if (!hasHandleChangeOnce && !value) {
      return [{ value: '', label: placeholder }, ...options];
    }

    return options;
  }
```
#### Solution

// French
Je propose d'ajouter une propriété au composant pour pouvoir le réinitialiser complètement.

// Engish
I suggest to add a property to the component to be able to reset it completely.

#### Screenshots

Before change 
![Capture d’écran 2019-10-06 à 23 15 11](https://user-images.githubusercontent.com/43414022/66276280-d8fef400-e891-11e9-9a11-6dd63a01fada.jpg)

After change
<img width="864" alt="image" src="https://user-images.githubusercontent.com/43414022/66276339-3f841200-e892-11e9-82b6-10c23f97cf04.png">

**Comment by arnaudforaison** [comment]
Agree to close this issue @samuel-gomez-axa ?

**Comment by samuel-gomez-axa** [comment]
yes i fixed it
