### ISSUE TITLE
Demo links does not work on github page

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-toolkit#46]
### Issue and Steps to Reproduce

The page below does not work :
https://axaguildev.github.io/react-toolkit/latest/demo/index.html

We should do that :
 that https://medium.com/@svinkle/how-to-deploy-a-react-app-to-a-subdirectory-f694d46427c1

**Comment by guillaumechervetaxa** [comment]
@oussamahamdaoui, do you want to try to do on this?

**Comment by triathletefr23** [comment]
I could do this if the issue isn't already taken.

**Comment by guillaumechervetaxa** [comment]
@oussamahamdaoui was working on it yesterday.

You can check out the "Project" Tabs, you will find many things available to do ^^

**Comment by triathletefr23** [comment]
It will be cool if he assigns this issue to himself to avoid having different persons work on the same issue.

**Comment by guillaumechervetaxa** [comment]
Close with #75
