### ISSUE TITLE
[Tabs] Tab does not become active when user clicks on it (+ types definition)

### ISSUE THREAD

**Issue by jhujhul** [AxaGuilDEv/react-toolkit#501]
### Issue and Steps to Reproduce
Tab does not become active when user clicks on it.  I have to manually set the `activeIndex` prop of the `Tabs` component to set the active `Tab`, and listen to the `onChange` prop. The component handled it itself on previous version (1.2).

I made a demo illustrating the problem (could not manage to load the css :/)
https://codesandbox.io/s/quizzical-framework-1m5zp

I have another problem with this component, the type definition for its props seems incorrect. 
`onChange`, `activeIndex` and `className` are required, I think they should be optional.

#### Versions
1.3.2

**Comment by guillaumechervetaxa** [comment]
C'est bizarre que cela fonctionne sur le storybook et ps sur ton exemple.
https://axaguildev.github.io/react-toolkit/latest/storybook/index.html?path=/story/tabs--default

https://github.com/AxaGuilDEv/react-toolkit/blob/master/storybook/storybook/src/packages/tabs/src/Tabs.stories.js

**Comment by jhujhul** [comment]
J'ai un peu regardé, le composant fonctionne du moment qu'on lui passe une fonction pour sa prop `onChange`. C'est pour ça que ça fonctionne sur le storybook et pas sur mon exemple. Je l'ai mis à jour.

Je veux bien faire une PR mais j'ai quelque soucis pour lancer le toolkit en local.
