### ISSUE TITLE
Permettre de fixer l'id Auto dans le pager (@axa-fr/react-toolkit-table)

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-toolkit#516]
Empêche de faire des snapshots en intégrant le toolkit, on est du coup obligé de le mocker entièrement.

**Comment by guillaume-chervet** [comment]
Tu peux deja le fixer ^^

**Comment by guillaumechervetaxa** [comment]
via le la props id

**Comment by youf-olivier** [comment]
Nop, marche pas :)

**Comment by youf-olivier** [comment]
Je fixe toujours mes Ids

**Comment by guillaume-chervet** [comment]
Je lai fait hier sur la demo du toolkit sur les pr que tu nas pas valider :p
