### ISSUE TITLE
fix(selectInput) has a null modifier in html by default

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-toolkit#520]
![image](https://user-images.githubusercontent.com/43414465/73360990-58cb2700-42a4-11ea-8c4f-65c31ef2dded.png)

my code :

  <SelectInput
                label="demo*"
                name={DEMO}
                id={DEMO}
                helpMessage="Ex : youhou"
                onChange={onChange}
                options={[
                  { value: 'Toto', label: 'Toto' }
                ]}
                forceDisplayMessage={hasSubmit}
                messageType="error"
                {...fields[DEMO]}
            >

**Comment by guillaumechervetaxa** [comment]
af-form__select-container--hasinfobulle
is in the wrong place for the select input

**Comment by xballoy** [comment]
I do not reproduce the bug. Is it still valid? Can you provide a more complete example?
