### ISSUE TITLE
Table.Header differents className

### ISSUE THREAD

**Issue by samuel-gomez-axa** [AxaGuilDEv/react-toolkit#522]
### Issue and Steps to Reproduce
the Table.Header component have a complexity on className and i don't understand why : https://github.com/AxaGuilDEv/react-toolkit/blob/master/packages/table/src/Header.tsx

the className should be the same than the Design System : https://axaguildev.github.io/react-toolkit/latest/design/molecules/table/

And i don't understand the "headers" props 
@guillaume-chervet do you know why ?

**Comment by arnaudforaison** [comment]
What do you hear about "has a complexity" ? Still current ?

**Comment by samuel-gomez-axa** [comment]
The header Table component check if "headers" props exists but return in twice cases a <thead>.
The difference between these cases is the className and a <Tr> wrapper.
I don't understand this usecase.
```javascript
if (headers) {
    return (
      <thead className={className}>
        <Tr>{children}</Tr>
      </thead>
    );
  }
  return <thead className="af-table-thead">{children}</thead>;
```
in my opinion, we should simplify this with just return 

```javascript
  return <thead className={className}>{children}</thead>;
```
