### ISSUE TITLE
Paging labels should be customizable or translated with i18n automatically

### ISSUE THREAD

**Issue by jmittelette** [AxaGuilDEv/react-toolkit#563]
### Issue and Steps to Reproduce
Paging labels should be customizable or translated with i18n automatically

#### Versions
1.3.4

#### Screenshots
None

#### Expected
All labels should be customizable

#### Actual
Actually, all labels are hard coded in french so we have "Afficher X éléments", "Précédent" and "Suivant"

#### Additional Details

- Installed packages

**Comment by guillaume-chervet** [comment]
Hi @jmittelette, it look like to be an easy first toolkit pull request to do. What do you think ?

**Comment by jmittelette** [comment]
Hello @guillaume-chervet , yes, good idea :)

**Comment by jmittelette** [comment]
Hello,

npm run bootstrap give me the followinf error: 
[11:10:15] Using gulpfile ~\Dev\react-toolkit\gulpfile.js
[11:10:15] Starting 'clean'...
[11:10:15] Finished 'clean' after 13 ms
lerna notice cli v3.13.4
lerna notice filter excluding "component-*"
lerna info filter [ '!component-*' ]
lerna info Bootstrapping 49 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@axa-fr/react-toolkit-storybook'
lerna ERR! npm install stderr:
**npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@axa-fr%2fstorybook-addons - Not found
npm ERR! 404
npm ERR! 404  '@axa-fr/storybook-addons@1.2.16' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404**

**Comment by jmittelette** [comment]
@guillaume-chervet  could you please help me ? (see my previous message bellow) Thanks ;)
