### ISSUE TITLE
[Date] Missing the previous and upcomming icons < > during year choice

### ISSUE THREAD

**Issue by fdescamps** [AxaGuilDEv/react-toolkit#570]
### Issue and Steps to Reproduce

Bonjour,
 
Je souhaite utiliser le composant DateInput du toolkit : https://axaguildev.github.io/react-toolkit/latest/storybook/index.html?path=/story/form-input-date--dateinput
Mais je constate que lorsque l’on veut naviguer dans les dates avec les années alors les « chevrons » ou autres ne s’affichent pas et on a des carrés gris à la place.
Idem lors de la navigation avec les mois, je constate que les mois sortent du cadre.
Savez-vous svp comment contourner ces soucis ? (en surchargeant la CSS je suppose mais est-ce « propre » ?)
 
Petite question : est-il svp possible de customiser le pas lors d’une navigation par années ?
Par défaut, on affiche 12 années mais on change les années une par une ? Peut-on les changer par 5, 12 ou autre ?
 
Merci d’avance pour votre aide,

#### Versions

^1.3.4

#### Screenshots

![datepicker](https://user-images.githubusercontent.com/1039390/77165334-5cb04400-6ab2-11ea-8026-b8fa00185d06.PNG)

#### Expected

View the icons

#### Actual

No icons

#### Additional Details

Proposal 👍 by Arnaud G. (thanks)

.react-datepicker__year-read-view--down-arrow--years-previous::after,
.react-datepicker__month-read-view--down-arrow--years-previous::after,
.react-datepicker__current-month--years-previous::after,
.react-datepicker__navigation--years-previous::after {
  content: '\EA0B';
  **text-indent: 0;**
  background-color: none;
}

.react-datepicker__year-read-view--down-arrow--years-upcoming::after,
.react-datepicker__month-read-view--down-arrow--years-upcoming::after,
.react-datepicker__current-month--years-upcoming::after,
.react-datepicker__navigation--years-upcoming::after {
  content: '\EA0A';
  **text-indent: 0;**
  background-color: none;
}

- Installed packages

**Comment by youf-olivier** [comment]
Carément en phase. Ce composant doit etre revu de bien des manières.

**Comment by Railk** [comment]
Hello,

Point de vue UX, pour les années le but était de faire du bloc à bloc donc, 12 année par 12 année en cliquant sur les les flèches grises

Rodney RICHARD - AXA

**Comment by arnaudforaison** [comment]
Est ce que les guidelines UX sont à jour sur le design system @Railk ?
A défaut que fait on sur cette implémentation ?

**Comment by samuel-gomez-axa** [comment]
de mon point de vue, si on refait le composant, il faudra essayer de ne pas trop changer le comportement actuel afin de pas perturber les utilisateurs qui utilisent déjà ce composant.

**Comment by youf-olivier** [comment]
Je prend le point au passage (j'ai commencé à ragder)

**Comment by youf-olivier** [comment]
Je vais deja mettre a jour react date picker qui a 2 majeurs de retard

**Comment by fdescamps** [comment]
Hi @youf-olivier 

Before updating date picker, may be we have to decide about : https://github.com/AxaGuilDEv/react-toolkit/issues/688 ?

Regards,

**Comment by youf-olivier** [comment]
On peut tout faire en un :)

**Comment by Railk** [comment]
Hello,

@samuel-gomez-axa, je serais d'avis qu'on change le comportement qui n'est pas très optimal (même si ils ont pris l'habitude du fonctionnement actuel) et je penses que ca sera bénéfique même avec le "nouveau" fonctionnement à apprendre.

On peut évoquer le sujet e Cop-Front-end, les nouveaux responsables du design system côté UX ont été déterminé ^^

@arnaudforaison je ne sais plus si on a mis ce détails dans les guidelines, je vais regarder.

**Comment by djaumes** [comment]
Bonjour à tous, 

Je prends la succession de @Railk - Rodney Richard - sur le chantier UX "Design System" (d'autres UX me rejoindront très prochainement). Je prends connaissance des différents tickets et j'apporterai très prochainement un maximum de réponses. 

En ce qui concerne celui-ci, je valide en hotfix l'incrément des années 12 par 12; au clic des flèches comme proposé par Rodney.

Pour l'évol visuelle et fonctionnelle, je pense qu'il faut se rapprocher de celui-ci: [](https://axaguildev.github.io/react-toolkit/latest/storybook/index.html?path=/story/form-input-datephone--datephone); plus intuitif, il règlera aussi l'écart entre desk et mobile. Je pense qu'une repasse UI pour coller au style des autres composants serait intéressante.

Je vais travailler avec l'équipe UX DS pour vous proposer une nouvelle solution prochainement.

**Comment by arnaudforaison** [comment]
Fix by #767
