### ISSUE TITLE
[DateInput/DatePhone] Different viewValue date format to handle

### ISSUE THREAD

**Issue by antoineblancke** [AxaGuilDEv/react-toolkit#612]
### Issue and Steps to Reproduce

We are using those components (DateInput and DatePhone) to handle both mobile mode and desktop mode in our applications. 

The fact is that the onchange method of those components returns a different format of the viewValue property (the screenshots show the difference). 

It forces the developers using those two components to handle two different format of date view values. Maybe, it could be better for the developer experience to use the same format (I don't know if it is possible) or to have a unique date component that handles both mobile and desktop mode.

#### Versions
1.3.4

#### Screenshots

With DateInput :
![image](https://user-images.githubusercontent.com/8201011/82036314-0cfc8c00-96a1-11ea-9a45-937f19d3a30d.png)

With DatePhone :
![image](https://user-images.githubusercontent.com/8201011/82036455-35848600-96a1-11ea-8800-5dc068af67bb.png)

#### Expected

Same viewValue format in the parameters of the onChange function for both components.

#### Actual
Different viewValue format in the parameters of the onChange function.

#### Additional Details

For example, if you use the [mw.validation](https://github.com/guillaumechervet/mw.validation) as it is suggested in the samples, you can have troubles validating a date format. It implies to transform date format before validating the date.

- Installed packages
"@axa-fr/react-toolkit-form-input-date": "^1.3.4",
"@axa-fr/react-toolkit-form-input-date-phone": "^1.3.7-alpha.0",

**Comment by guillaumechervetaxa** [comment]
Thank you Antoine for the feedback.
Seems a good idea to normalise viewValue.

For information I'am using it like this, but I'am not sure it is intergrable in the toolkit. We need to discuss the rule of we use mobile version and How.

import React from 'react';
import { isMobile } from 'react-device-detect';
import { DateInput } from '@axa-fr/react-toolkit-form-input-date';
import { DatePhoneInput } from '@axa-fr/react-toolkit-form-input-date-phone';

const AdvaloremDateInput = props => {
    const Date = isMobile ? DatePhoneInput : DateInput;
    return <Date {...props} />;
};

export default AdvaloremDateInput;
