### ISSUE TITLE
Suggestion: optionally disable error message memorization

### ISSUE THREAD

**Issue by rpetigny** [AxaGuilDEv/react-toolkit#62]
### Issue and Steps to Reproduce

On TextInput (and other Inputs), message prop is updated on FieldError only when focus change.
This can lead to many user actions before field is valid.

### Versions
All

#### Expected
Disabled the message memorization in FieldForm

#### Actual
This behavior cannot be overriden.

### Additional Details
Example :
I have a TextInput required and with some regex pattern validation, and a submit button.
I click on submit button => required message appears
I fill TextInput with bad value, required message still there
I click somewhere else => bad value message appears
I fill TextInput with correct value, bad value message still there
I click somewhere else => bad value message disappears
I can now submit my form

**Comment by guillaumechervetaxa** [comment]
Hello Romain,

The props "forceDisplayMessage" disable the message memorization in FieldForm. It is its role.

**Comment by guillaumechervetaxa** [comment]
Can you show us some code ? I think we need more context :)

**Comment by arnaudforaison** [comment]
This is issue can be close ?
