### ISSUE TITLE
style website make lerna bootstrap crash on windows 

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-toolkit#621]
![image](https://user-images.githubusercontent.com/43414465/83775521-51b78980-a687-11ea-9083-dc4afc1b3957.png)

I can reproduce it on my personal laptop

**Comment by xballoy** [comment]
Cf https://github.com/gulpjs/gulp/issues/2324
As a workaround you can use Node 10 to fix this issue
