### ISSUE TITLE
Use exact version in dependencies / devDependencies

### ISSUE THREAD

**Issue by xballoy** [AxaGuilDEv/react-toolkit#629]
We should use exact versions in the dependencies and devDependencies to:
- have a reproducible build
- have a good control on the dependencies we use (some might not respect semver)
- be able to use a specific version of the toolkit (see bellow)

Eg: 
- I have `@axa-fr/react-toolkit-all` version 1.3.13 in my package.json
- I want to rollback to version 1.3.12
- Because all dependencies of 1.3.12 (see [package.json](https://github.com/AxaGuilDEv/react-toolkit/blob/v1.3.12/packages/all/package.json)) are "^1.3.12"  I still have the 1.3.13 when I do a npm install. The only way to force the 1.3.12 is to list all the dependencies in my package.json.

**Comment by xballoy** [comment]
I also had an issue in #625 with `@types/react-modal": "^3.6.0` which, for some reason, decided to pull the 3.10.5 which breaks the Modal component.

**Comment by xballoy** [comment]
@youf-olivier what do you think?

**Comment by youf-olivier** [comment]
We have somes issues with packages. I don't really know what we can do exactly. We discussed about this few days ago with @arnaudforaison . You can see that with him. And then, I dont know if it is the same problem 🧐

**Comment by xballoy** [comment]
Ok, so maybe we can work on this when fixing #627
