### ISSUE TITLE
Failed images of npm versions

### ISSUE THREAD

**Issue by triathletefr23** [AxaGuilDEv/react-toolkit#64]
### Issue and Steps to Reproduce

Failed npm packages' versions on the main page

### Screenshots

![image](https://user-images.githubusercontent.com/9766356/52333472-a1d3fc80-29fd-11e9-900a-4a26e11c8309.png)

**Comment by guillaumechervetaxa** [comment]
I may think that F5 on your browser fix the problem ^^

**Comment by triathletefr23** [comment]
Sure!
