### ISSUE TITLE
Popover blocks click events

### ISSUE THREAD

**Issue by rpetigny** [AxaGuilDEv/react-toolkit#643]
https://github.com/AxaGuilDEv/react-toolkit/blob/5aec25bd302c28dcc181791d0cae5e8bc81d7ae9/packages/popover/src/Popover.js#L36
https://github.com/AxaGuilDEv/react-toolkit/blob/5aec25bd302c28dcc181791d0cae5e8bc81d7ae9/packages/popover/src/Popover.js#L45

New behavior on popover prevents any other click action on the page

**Comment by xballoy** [comment]
Can you have a look at my PR to check if it solves your issue?
