### ISSUE TITLE
[Bug] package.json file of react-toolkit-all package referencing latest minor version of sub-dependencies instead of exact version

### ISSUE THREAD

**Issue by daniel-salome-axa** [AxaGuilDEv/react-toolkit#667]
### Issue and Steps to Reproduce

The package.json configuration file of "react-toolkit-all" package is referencing latest minor version of its sub-dependencies (with the caret ^) but it should reference their exact version instead.

When we set :

"@axa-fr/react-toolkit-all": "1.2.12"

in the package.json file of our own project, when I do a "npm install" with a clean npm cache and no package-lock.json file
it download all the sub-dependencies having 1.3.16 version.

#### Versions

All (checked with latest version and in 1.2.12)

#### Screenshots

![image](https://user-images.githubusercontent.com/70018804/90890333-0b3a1700-e3ba-11ea-83de-865c14d49f64.png)

- Installed packages :

"@axa-fr/react-toolkit-all": "1.2.12"

**Comment by arnaudforaison** [comment]
Lerna with `--exact` must do the job.
https://github.com/lerna/lerna/issues/2040#issuecomment-483772196

**Comment by xballoy** [comment]
It was fixed by #680 
If you use a version >= 1.3.21 you should not have this issue anymore.

Feel free to reopen this issue if you still reproduce the bug.
