### ISSUE TITLE
Lien entre les packages

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-toolkit#670]
En lien avec la PR en cours 

https://github.com/AxaGuilDEv/react-toolkit/pull/668

Quand je met un package (exemple alert) a jour qu'un autre depend de lui, il semble pas que les liens soit encore ok.

Ici j'ai rajouté un role dans le alert, et du coup son snapshot se met a jour. Normalement le snapshot du summary doit aussi etre a jour (il a été poussé ici), mais lors du lancement des tests, ça passe pas, le lien est pas fait entre les deux.

**Comment by samuel-gomez** [comment]
petite précision, ça fonctionne correctement en loca, tu confirmes @youf-olivier ?

**Comment by youf-olivier** [comment]
Les snapshots ont été générés en local sur ma machine. C'est lors de la build que les snapshots matchent pas

**Comment by arnaudforaison** [comment]
La PR a été mergé, qu'est ce qui bloque ou qui doit être investigué ?

**Comment by youf-olivier** [comment]
J'ai du virer les snapshots pour que la PR passe, pour le moment a mon avis y a rien de corrigé

**Comment by xballoy** [comment]
Should be fixed as we do not have dependencies with local path anymore as we flatten / remove "sub-projects" in #731 and #728.
