### ISSUE TITLE
[bug] Installation for contribute on Windows - css files generation

### ISSUE THREAD

**Issue by samuel-gomez-axa** [AxaGuilDEv/react-toolkit#671]
### Issue and Steps to Reproduce

some files are not generated when installing the toolkit on Windows.

```npm install```

**Comment by guillaume-chervet** [comment]
npm run storybook fail

![image](https://user-images.githubusercontent.com/52236059/91811863-75f81780-ec30-11ea-974c-5cb4823af193.png)

**Comment by samuel-gomez-axa** [comment]
resolve by #674
