### ISSUE TITLE
Improve contributors' experience with more documentation.

### ISSUE THREAD

**Issue by gcruchon** [AxaGuilDEv/react-toolkit#693]
### Issue and Steps to Reproduce

Documentation needed for a better help to constributors.

#### Versions

1.3.21

#### Expected

- List of supported browsers, for contributor to test with them
- More details about scripts and what they do
- Some How-Tos (like: how to make your CSS changes available in the storybook)
- Some Guidelines (test guidelines: "what to test and how", a detail of the architecture of a component)
- Some useful tools (like VM for testing on various browsers)

#### Actual

Contributor have to dig into the code, to understand more how things work.

**Comment by arnaudforaison** [comment]
CONTRIBUTING.md file seems to explain some of script do. Not enough ? How do more ?
Design system, have guidelines.
Tools like ... ?

**Comment by gcruchon** [comment]
If it's OK for you, you can assign this issue to me and I can submit a first version that we can all improve during the PR.
