### ISSUE TITLE
concurrently not in devDependencies of storybook packages.

### ISSUE THREAD

**Issue by gcruchon** [AxaGuilDEv/react-toolkit#695]
### Issue and Steps to Reproduce

Impossible to start sotrybook if `npm i` has not been triggered on root folder
`concurrently` is not found because not in the devDependcies of storybook `package.json`.

#### Versions

v1.3.21

#### Expected

`concurrently` should be in the devDependencies of storybook packages

#### Actual

`concurrently` is not the devDependencies of storybook packages

#### Additional Details

I happened to find this issu while trying to launch storybook (`npm run storybook`) just after cloning the forked repo (and forgetting to run `npm i` on the root folder, silly me!)

**Comment by xballoy** [comment]
I removed `concurrently` from the storybook in #700  it was used to launch only _one_ command 😅

**Comment by gcruchon** [comment]
Thanks. I'll close the issue, then.
