### ISSUE TITLE
Refacto du composant Date

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-toolkit#712]
Hello je fais une issue pour rassembler tout ce qui concerne le composant date.

Comme par exemple la fusion ou du moins la rééxamination des deux composants date

#688 : Travail sur les deux composants : Fusion ? Avec Option ? le Phoen-Date est juste un wrapper du composant natif

#570 : LE React Date Picker est trop vieux : Je vais l'update

#690 : Bug sur la saisie Manuelle.

De plus Je dois voir avec @Railk pour le Design System.

**Comment by djaumes** [comment]
Bonjour @youf-olivier , je prends la succession de Rodney Richard sur le chantier "Design System". Je m'occupe de répondre aux différents tickets très prochainement.

**Comment by youf-olivier** [comment]
Hello. J'avais taggué Rodney car ça parlait de mettre a jour le composant dans le DS. Pour le reste c'est du technique. Je te laisse revenir vers nous sur ce point.

**Comment by djaumes** [comment]
@youf-olivier :  côté UX, on s'est mis d'accordsur les principes du "nouveau" datepicker:
- une révision fonctionnelle principalement [datepickerv3](http://9xzhq7.axshare.com/#g=1&p=datepicker_v3);
- supprimer la version mobile, un seul datepicker dans le toolkit;
- revoir les guidelines pour un usage limité aux dates proches (pas de datepicker pour une date de naissance par ex.);

Est ce que cela te semble faisable techniquement?

Pour la nav annees/mois, je propose:
Générer la liste d'années à +30/-100 ans, centrée sur l'année en cours;
Générer la liste de mois +6 /-6 mois, centrée sur le mois en cours;

**Comment by Xym618** [comment]
> Pour la nav annees/mois, je propose:
> Générer la liste d'années à +30/-100 ans, centrée sur l'année en cours;
> Générer la liste de mois **+5 /-5 ans,** centrée sur le mois en cours;

Correction : on passe au **+5 /-5 ans,** pour la liste de mois

**Comment by arnaudforaison** [comment]
Il faudra favoriser l'usage d'une lib si le besoin est répondu à 80%
