### ISSUE TITLE
Tabs: onChange shouldn't be mandatory + more typescript support

### ISSUE THREAD

**Issue by vivo87** [AxaGuilDEv/react-toolkit#719]
### Issue and Steps to Reproduce

Upon adding Tabs component: 

`<Tabs>
        <Tabs.Tab title="1">
           Content 1
        </Tabs.Tab>
        <Tabs.Tab title="2">
          Content 2
        </Tabs.Tab>
      </Tabs>`

the tab change won't work because onChange is undefined. We must add a `<Tabs onChange={console.log}>` in order for tab change to work. 

Besides, with typescript the props validations didn't work because it require all props  ...

> Overload 1 of 2, '(props: Readonly<TabsCoreProps>): Tabs', gave the following error.
    Type '{ children: Element[]; onChange: { (...data: any[]): void; (message?: any, ...optionalParams: any[]): void; (message?: any, ...optionalParams: any[]): void; }; }' is missing the following properties from type 'Readonly<TabsCoreProps>': className, activeIndex

we must bypass by adding our own declaration.

`declare module "@axa-fr/react-toolkit-tabs" {
  const Tabs: any;
  export default Tabs;
}`

#### Versions
^1.3.4

#### Expected

Tab change to work on click on a Tab Item

#### Actual

Tab change not working without onChange

#### Additional Details

- Installed packages

**Comment by arnaudforaison** [comment]
In which version do you see that ?

**Comment by vivo87** [comment]
> In which version do you see that ?

^1.3.4

**Comment by xballoy** [comment]
It looks like it was fixed in version [1.3.14](https://github.com/AxaGuilDEv/react-toolkit/blob/master/CHANGELOG.md#v1314) by #615 .
Do you still reproduce it with the latest version?

**Comment by vivo87** [comment]
yeah maybe i haven't tested the latest version, i'll try it hopefully there won't be any breaking css change because i had to overwrite severals classes. Thanks !
