### ISSUE TITLE
[Issue][Boostrap] Regression grid.css et reboot.css

### ISSUE THREAD

**Issue by DanneelsSophie** [AxaGuilDEv/react-toolkit#764]
#### Versions
Version 
**"version":"1.3.23"**
The issue will be the version of boostrap @samuel-gomez @samuel-gomez-axa 
#### Expected
![image](https://user-images.githubusercontent.com/15892424/96879240-170a8e00-147c-11eb-8937-1602b46e6c73.png)

#### Actual
![image](https://user-images.githubusercontent.com/15892424/96879331-36092000-147c-11eb-8a4d-19f2969b1338.png)

#### Additional Details

- Installed packages

**Comment by arnaudforaison** [comment]
Je ne comprends pas bien le besoin. Est ce que tu pourrais détailler stp ?

**Comment by DanneelsSophie** [comment]
Bonjour,

Avec Samuel Gomez, on s'est apperçu d'une regression au niveau du css qui serait dû au fichier grid.css et reboot.css, en mettant des anciens on remarque qu'on avait plus la regression. Tu peux remarquer dans les deux captures qu'il y a une différence au niveau du trait et au niveau des emplacements :( !

**Comment by DanneelsSophie** [comment]
Je vais essayer de voir pour la traiter ^^"
