### ISSUE TITLE
Lint rules

### ISSUE THREAD

**Issue by xballoy** [AxaGuilDEv/react-toolkit#773]
Currently we have the following ESLint rules:
- [eslint-config-airbnb-typescript](https://www.npmjs.com/package/eslint-config-airbnb-typescript): a drop-in replacement for `eslint-config-airbnb`, decorating it with TypeScript support
- [eslint-config-react-app](https://www.npmjs.com/package/eslint-config-react-app)
- [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier): we are using Prettier for formatting

However we changed the severity of several rules:
## [Core](https://eslint.org/docs/rules/)
- [linebreak-style](https://github.com/eslint/eslint/blob/master/docs/rules/linebreak-style.md): off
- [no-param-reassign](https://github.com/eslint/eslint/blob/master/docs/rules/no-param-reassign.md): warning
- [no-prototype-builtins](https://github.com/eslint/eslint/blob/master/docs/rules/no-prototype-builtins.md): warning

## [Import](https://www.npmjs.com/package/eslint-plugin-import)
- [named](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md): warning
- [no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md): warning
- [no-named-as-default](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-as-default.md): warning
- [no-unresolved](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md): warning
- [prefer-default-export](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/prefer-default-export.md): off

## [a11y](https://www.npmjs.com/package/eslint-plugin-import)
- [anchor-is-valid](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md): warning
- [aria-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/aria-role.md): warning
- [control-has-associated-label](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/control-has-associated-label.md): warning
- [label-has-associated-control](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md): warning
- [no-autofocus](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-autofocus.md): warning
- [no-noninteractive-element-interactions](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-interactions.md): warning

## [React](https://github.com/yannickcr/eslint-plugin-react)
- [button-has-type](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md): warning
- [destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md): warning
- [jsx-filename-extension](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md): warning
- [forbid-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md): off
- [jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md): off
- [jsx-closing-tag-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md): off
- [jsx-props-no-spreading](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md): warning
- [no-multi-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md): off
- [no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md): warning
- [no-array-index-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md): warn
- [no-unescaped-entities](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md): warning
- [prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md): off
- [require-default-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md): warning

## [Typescript](https://github.com/typescript-eslint/typescript-eslint)
- [no-unused-vars](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md): warning
- [no-use-before-define](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md): warning

---

Should we keep them all? Should we simplify them? @youf-olivier @samuel-gomez @arnaudforaison

**Comment by arnaudforaison** [comment]
I'm agree with you, toolkit need strict rules but more simple implementation. Maybe only based on Airbnb rules

**Comment by youf-olivier** [comment]
We have to validate our rules and fix all files in one pass.

**Comment by xballoy** [comment]
I can work on that to fix them then switch the rules from warning to error.

**Comment by xballoy** [comment]
Do we want to keep this rule: [jsx-props-no-spreading](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md)? All our code use props spreading...

**Comment by arnaudforaison** [comment]
> Do we want to keep this rule: [jsx-props-no-spreading](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md)? All our code use props spreading...

This must be removed.
