### ISSUE TITLE
Storybook not refreshed (stuck on 1.3.14)

### ISSUE THREAD

**Issue by jmittelette** [AxaGuilDEv/react-toolkit#781]
### Issue and Steps to Reproduce
Hello there,

When I want to display the latest version of the React Toolkit Storybook on github (using https://axaguildev.github.io/react-toolkit/latest/storybook/index.html?path=/story/get-started--introduction), the storybook is stuck on version 1.3.14.

It seems that something prevents the Storybook update after new releases of React Toolkit.

Could you please fix this

Thanks

**Comment by arnaudforaison** [comment]
https://github.com/AxaGuilDEv/react-toolkit/pull/731/files#diff-62b793be802a848c8d68cd089ed7b6d030ba14cb97f72a1fca46104ce11e9d97

**Comment by arnaudforaison** [comment]
Fixed in #731 
https://github.com/AxaGuilDEv/react-toolkit/pull/731/files#diff-62b793be802a848c8d68cd089ed7b6d030ba14cb97f72a1fca46104ce11e9d97
