### ISSUE TITLE
[Discussion] Merge vs Rebase

### ISSUE THREAD

**Issue by gcruchon** [AxaGuilDEv/react-toolkit#786]
Hello,

In a PR, I was told that it's useless for me to rebase my code while waiting for reviews because, anyway, my code would be squashed into master.

I like to rebase my code because I think it's cleaner in the history.

But I noticed that some PR are merged and not squashed (or rebased - if you'd like to keep the commits) into master.

<img width="744" alt="merged-spotted-in-history" src="https://user-images.githubusercontent.com/1456883/97776102-d8ed2880-1b65-11eb-922d-12e6e67eec1c.png">

Wouldn't it be great to agree all on 1 way to do things? (merge / rebase / squash)

Second thing, I see some merge in working branched (e.g. `fix(storybook): change the brandUrl to match the spirit of the project (#770)` into branch `model/aria`). Isn't it a better practice to rebase your working branch (is was only 1 commit behind) ?

Third thing, branch name seems not to be homogeneous:
- feat/demo-login
- feature/coreTypes
- feature/cssTypeIssue
- feature/Date
- feature/debouce-behavior-to-display-message
- feature/home-add-filters
- feature/migrate-ts-formcore
- feature/number-use-input-number
- feature/publishNext
- feature/upgradeStorybook
- fix/remove-carret
- fix/run-websites
- page-with-tabs-sample
- test/modal
- update/rc-slider
- wip/design-system

What's the standard? Gitflow? "feat" ou "feature"?

**Comment by xballoy** [comment]
When a PR is automatically completed with Mergify commits are [squashed](https://github.com/AxaGuilDEv/react-toolkit/blob/master/.mergify.yml#L10).
However when done manually, it's up to the maintainer to choose what to do...
I would also prefer that we always do the same (merge or squash, just pick one).

Regarding the branches, no convention is chosen. I think that as long as we don't need one we should create one.

**Comment by youf-olivier** [comment]
Dsl je répond en Fr pour pas y passer 3h

> Hello,
> 
> In a PR, I was told that it's useless for me to rebase my code while waiting for reviews because, anyway, my code would be squashed into master.
> 

Je pense qu'on s'est pas compris sur cette PR dont tu parles. Quand je te disais que t'avais pas besoin de rebase avant de faire une PR c'est qu'à l'époque ton code allait etre mergé dans la master. Et donc si pas de conflit ca sert a rien de rebase **avant**, le resultat est le même après le merge.

Faire un rebase au moment de finir la PR c'est détruire de l'information. Avoir un historique "plat" c'est esthétique et plus facile, mais on a perd les informations des différentes branches et du coup si on voulait revert une PR entière on est mort. Du coup il faut squash toutes les PR, et perdre les commits.

Du coup tu as raison Gilles on doit peut etre le mettre plus explicitement, mais pour moi on doit choisir entre deux modes :
- Soit on squash toutes les PR et le nom de la PR sera un unique commit et comme ça on flat l'historique en gardant l'empreintes des PR au lieux des commits (On perd les découpages en commit) : 
- Soit on Fait du GitFlow avec des merge vers la Master et on garde tous les commits et toutes les infos de PR mais c'est loins lisible. 

Pour ce qui est du merge chelou, j'ai testé le bouton qui apparait quand ta branche n'est plus a jour avec la master, c'est ce clic qui a fait un merge de master vers la branche en court de PR. Perso je suis pas super fan de ce nouveau truc apres test.

**Comment by JLou** [comment]
Sorry to unearth the topic, but here are my 2 cents. As a developper it is in my opinion preferable to only have merge commits in master.
This allows to "_group_" a set of modifications, and makes it easier when going through history later on.
While it is great to rebase before merging the PR (avoiding potentially having 2 merge commits, one in the feature branch, the other on master), I prefer my PRs to be merged.

**Comment by gcruchon** [comment]
@youf-olivier : Ce bouton est nul, en effet, il a tout cassé chez moi, j'ai du faire un rebase. C'est réparable, mais faut y aller en mode interactif...

@JLou : I agree that merge commits from PR to master are good if it's readable in the git history. That means that you should always rebase your branch to last master's commit just before the merge. In open-source that could be complicated: it's already hard to get reviews... and you will restart from scratch because of last minute rebase... Or maybe we can configure github to keep review on a simple rebase from master?
