### ISSUE TITLE
CollapseCardBase has collapse prop inverted

### ISSUE THREAD

**Issue by JLou** [AxaGuilDEv/react-toolkit#787]
### Issue and Steps to Reproduce
CollapseCardBase is closed with when collapse prop is false, and is open when collaspe is true.

```jsx
            <CollapseCardBase collapse={false}>
              <CollapseCard.Header>Raison sociale</CollapseCard.Header>
              <CollapseCard.Body>gze</CollapseCard.Body>
            </CollapseCardBase>
```
#### Versions
1.3.11

#### Screenshots
![image](https://user-images.githubusercontent.com/183460/97869921-81d88680-1d12-11eb-8205-c55b446539ea.png)
![image](https://user-images.githubusercontent.com/183460/97869938-8866fe00-1d12-11eb-8177-a2a397907682.png)

#### Expected
CollapseCardBase is closed with when collapse prop is true, and is open when collaspe is false.

#### Actual
CollapseCardBase is closed with when collapse prop is false, and is open when collaspe is true.

#### Additional Details
The 2 solutions I have in mind are inverting the behaviour of the booleans and keeping the prop name, or changing the name of the prop to something like `isOpen`.

Unfortunately, this will introduce a breaking change. Although, if a new property is introduced, we can keep the existing one and making the new one override it if set, deprecating the usage of `collapse`.

**Comment by johnmeunier** [comment]
I think the second solution is the best to avoid breaking change and improve the prop name.

**Comment by johnmeunier** [comment]
Après avoir creusé le code du composant avec @LunarzFR , on en est venu à la conclusion que ce composant mérite une refacto complète. Cette refacto entrainerait de gros breakings change, donc peut-être laisser ce composant en l'état et sortir une v2. Voici ce que nous proposons  afin de simplifier l'utilsation
- Le composant CollapseCardBase devient le composant CollapseCard. 
- Le composant est de base stateful avec une prop isOpen et non collapse. 
- Par défaut, le onToggle fait un setIsOpen(!isOpen). Si il y a une méthode passé en prop à onToggle, surcharge du comportement par défaut
- Possibilité de cliquer dans tout le header pour trigger le onToggle (problème avec le padding)
- Suppression des sous composants Body et Header
- Passer le header en prop au Collapse (string ou JSX autorisé)
- Passer le body du Collapse en children 
- Dans le composant Accordion, suppression du composant onlyOne (à gérer à l'intérieur du composant)

**Comment by LunarzFR** [comment]
Suite à un point avec @johnmeunier ,nous envisageons de partir sur :
- Renommage de la prop collase en isOpen (inversion de sa valeur)
- Modification du header pour avoir le clic sur toute la surface
- Assembler CollapseCard avec CollapseCardBase
- Suppression de Accordion Single
