### ISSUE TITLE
The Tabs component can't accept only one Tab children

### ISSUE THREAD

**Issue by johnmeunier** [AxaGuilDEv/react-toolkit#791]
### Issue and Steps to Reproduce

The Tabs component can't accept only one Tab.

https://axaguildev.github.io/design-system/molecules/tabs/

#### Expected

In some case, it's necessary for a the Tabs component (the one who contains the tabs) to accept only one tab in children. For example when the tabs are dynamically generated.

#### Actual

For the moment, you have an error when you try to pass only one tab because the map is impossible.

**Comment by arnaudforaison** [comment]
I don't understand use case with only one tab ?

**Comment by arnaudforaison** [comment]
Est ce que tu es sur qu'en terme d'UX une seule Tab est possible ? @djaumes @johnmeunier

**Comment by djaumes** [comment]
C'est pas génial en effet, 
tout dépend si le **_titre du tab_** apporte du sens ou non dans le contexte de la page.

Si ça apporte du sens au contenu on peut le garder,
Si ça n'apporte rien c'est inutile de le garder.

**Comment by arnaudforaison** [comment]
Pour moi s'il y a qu'une seule tab c'est un titre (car tabs = section).

**Comment by johnmeunier** [comment]
J'ai un cas concret dans un projet où une activité pour être sur différents marché, mais également sur un seul. Cette notion est évidemment dynamique. J'ai un tab pour choisir le marché des données que je suis en train de configurer : 

![Capture d’écran 2021-02-16 à 08 01 29](https://user-images.githubusercontent.com/14071674/108029300-801aa080-702d-11eb-96a7-451a6e17f326.png)

Par contre si mon activité est sur un seul marché :  

![Capture d’écran 2021-02-16 à 08 01 12](https://user-images.githubusercontent.com/14071674/108029343-8c066280-702d-11eb-9602-7d5ca0f05d0a.png)

Deux raisons ici de laisser un tab. Facilité de développement évidemment et surtout cohérence UX. La page aurait eu une apparence très différente entre les activités mixe et mono marché car le composant tab impose un certain style (fond blanc, gros bouton bleu, etc). Le fait d'afficher un seul tab n'a jamais été remonté lors des tests comme quelque chose de mauvais. 

Une autre solution possible aurait été de toujours afficher les deux mais de mettre en grisé celui qui ne peut être actif mais on aurait affiché une info totalement inutile dans notre cas.

**Comment by djaumes** [comment]
D'un point de vue accessibilité et logique (un tab = une section titre et P), Arnaud a raison. D'un point de vue l'exemple, le tab fait vraiment sens... Si on arrive à faire un joli titre dans le bloc blanc, ça me va aussi :) Pose la question sur le channel UX/Dev!

**Comment by johnmeunier** [comment]
Est-ce que ca serait pas l'occasion de challenger le design des tabs pour faire quelque chose de moins tranchant, plus épuré ? Je pense notamment à ce fond bleu, cette bordure, ces gros boutons bleus, etc

**Comment by djaumes** [comment]
@johnmeunier Très bonne idée. Je te propose qu'on prenne le sujet en point hebdo design system, qu'on évoque les problématiques et solutions envisageables sur le réfacto.
