### ISSUE TITLE
Replace JSNExt by Module / Add ES2015 transpiled Files

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-toolkit#812]
We have to change JSNext by Module (it seems to be deprecated) 

But the target of module has to be a Trapiled ES2015 file, not a common JS or a TS file. I think we have to dig deeper with Aymeric about that.

**Comment by arnaudforaison** [comment]
Maybe do the fix into 2.0.0 when all components will be migrated to Typescript ?

**Comment by JLou** [comment]
Update: the issue with the style wasn't actually that the file isnt present, but that when you use modules, the import for files is supposed to be 
```ts 
const logo = new URL(
  '@axa-fr/react-toolkit-core/dist/assets/logo-axa.svg',
  import.meta.url
).href;
```

But that syntax doesn't work when building for es2015 :(

Sooooo, 2 solutions:
- Don't build for cjs
- Use a bundler like rollup/snowpack or whatever for the packages using images (just the footer actually)

**Comment by JLou** [comment]
A WIP branch is available [here](https://github.com/JLou/react-toolkit/tree/feature/modulebuild) for testing

**Comment by arnaudforaison** [comment]
The solution found is to add a declaration file into include prop of tsconfig with
```
declare module *.svg
```
So any more compiler error and I think it's do the trick
