### ISSUE TITLE
Type date in date field

### ISSUE THREAD

**Issue by johnmeunier** [AxaGuilDEv/react-toolkit#82]
It's not possible to type a date in the date component. 

To improve the UX and the workflow, it will be good if the component accept keyboard input

**Comment by guillaumechervet** [comment]
I do not understand what you want @johnmeunier. Do you have more details/informations?

**Comment by johnmeunier** [comment]
For the moment, I'm not able to type in a dateinput field, I have to use the datepicker. It's maybe a bug, we have this problem on GDS

**Comment by gcruchon** [comment]
Is it duplicate with #690 ? ping @legrandkhan

**Comment by arnaudforaison** [comment]
No it's not duplicated. I think this issue isn't more valid. Agree @johnmeunier ?

**Comment by johnmeunier** [comment]
Agree, it seems fixed
