### ISSUE TITLE
Logo not included with the Footer

### ISSUE THREAD

**Issue by gprst** [AxaGuilDEv/react-toolkit#821]
### Issue and Steps to Reproduce

1) On my project : `yarn add @axa-fr/react-toolkit-all`
1) On my App.js : `import { Footer } from '@axa-fr/react-toolkit-layout-footer'`
1) Figured out I also had to import the SASS file (which is only mentioned on the "Getting started" part of the project README, I think it should be more clear you need to manually import the SASS file for every single component you use) :
`import '@axa-fr/react-toolkit-layout-footer/dist/footer.scss'`
1) The AXA logo isn't included

#### Versions

1.4.0-alpha.0

#### Screenshots

![catastrophe](https://user-images.githubusercontent.com/32643653/101179679-d9884b80-364a-11eb-9d78-d8bbf625af66.png)

#### Expected

No additional steps should be required to have the AXA logo on the footer

#### Actual

I have to figure out a workaround to have the logo displayed

**Comment by arnaudforaison** [comment]
Yes it's a bug.

But you can overidde it with `icon` prop

```js
import logo from '@axa-fr/react-toolkit-core/dist/assets/logo-axa.svg';
<Footer icon={logo} {...otherProps} />
```
