### ISSUE TITLE
Popover - ajustement padding

### ISSUE THREAD

**Issue by Xym618** [AxaGuilDEv/react-toolkit#828]
Bonjour,

Voici quelques styles à corriger sur les composants suivants: 

**Popover:**
- Correction de padding sur la partie intérieur du contenu de la bulle: 8px 16px 8px 16px;
![image](https://user-images.githubusercontent.com/73350886/104619901-a942bc80-568e-11eb-9408-738807e1070e.png)
![image](https://user-images.githubusercontent.com/73350886/104619304-fe320300-568d-11eb-8165-09eda23fadb4.png)

- Centrer l'exemple de Popover sous Storybook pour montrer les 4 positions de Popover: top, right, bottom et left.

**Comment by arnaudforaison** [comment]
Le padding est bien à la bonne taille, la story qui a permis de créer cette issue est composée d'un tooltip custom.
Le composant Popover (et non PopoverBase) possède bien les bonne propriétés.
