### ISSUE TITLE
[help] - infobulle - CSSFIX

### ISSUE THREAD

**Issue by djaumes** [AxaGuilDEv/react-toolkit#831]
**Design System :** 
![Capture d’écran 2021-01-19 105154](https://user-images.githubusercontent.com/53373404/105017697-5e38f880-5a44-11eb-9415-cb3b4fc4593e.png)
![Capture d’écran 2021-01-19 105229](https://user-images.githubusercontent.com/53373404/105017777-7872d680-5a44-11eb-8ffe-53e7bab49620.png)

**Sketch:**
https://www.sketch.com/s/73328776-a6d4-47b7-a18b-fbb294f8d790/a/ZoqEY7#Inspector

Avoir le (i) centré sur la hauteur du champ de formulaire

(i) 
bg: #3032C1 
width: 20px
heigth: 20px
font: TimesNew roman bold italic 700
size:16

Description
bg :#3032C1 
padding: 8px 16px 8px 16px
texte
![Capture d’écran 2021-01-19 105333](https://user-images.githubusercontent.com/53373404/105017903-a0623a00-5a44-11eb-83b4-d1418b74ad4d.png)

**Comment by arnaudforaison** [comment]
`.af-more-help {
   font-weight: bold;
    font-family: Georgia;
    font-style: italic;
    font-size: 1.2rem;
}`
Et size de width & height à 2rem
