### ISSUE TITLE
[Storybook] Brainstorm - Deploy Storybook on PR

### ISSUE THREAD

**Issue by jforatier** [AxaGuilDEv/react-toolkit#849]
Hello,
Je vous propose de discuter ici pour trouver le moyen d'avoir un **Storybook déployé** sur chaque PR.

Vous connaissez les possibiltiés offerts par Storybook pour versionné le contenu ? (Genre une liste déroulante de versions)

Quelques approches possibles, n'hésitez pas à enrichir.
- Un dossier/un storybook ? (https://github.com/AxaGuilDEv/AxaGuilDEv.github.io/tree/master/react-toolkit)
- Utilisez le CI/CD pour instancier un Front On-Demande (Netlify ? FirebaseHosting? ...)
- Des idées ?

**Comment by arnaudforaison** [comment]
@johnmeunier, @youf-olivier et @samuel-gomez vous en pensez quoi ?
Je ne connais pas assez Netlify mais de ce que je connais cela peut être une bonne idée. Déploiement facile du storybook buildé, surement moyen d'avoir une durée de rétention. 

Est ce qu'il y aurait un coût à prévoir pour cette solution ?

D'autres solutions à proposer ?

**Comment by youf-olivier** [comment]
Y a pas @romuleald qui sait faire ça aussi ?

**Comment by romuleald** [comment]
Avec netlify c'est hyper simple, mais il faut voir si c'est accepté en interne

**Comment by johnmeunier** [comment]
C'est fait, j'avais pas vu l'issue je l'ai fait entre deux avec @arnaudforaison, je présente ça en cop front

**Comment by arnaudforaison** [comment]
Fait avec Chromatic sur les PR
