### ISSUE TITLE
Difficult to run storybook on Windows 7

### ISSUE THREAD

**Issue by guillaumechervet** [AxaGuilDEv/react-toolkit#85]
### Issue and Steps to Reproduce

clone the project
npm i
npm run boostrap # some error appears during the command "gulp prepare"

![image](https://user-images.githubusercontent.com/10611904/53005799-dd25f080-342b-11e9-8468-349c6db3c581.png)

The consequence is that it it impossible to run storybook (the demo works)

I had to run again manualy the command, in order to be able the storybook (npm run storybook)
so I ran :
npx gulp prepare

Then storybook works
![image](https://user-images.githubusercontent.com/10611904/53005728-b8ca1400-342b-11e9-8f35-efeda6116e08.png)

**Comment by arnaudforaison** [comment]
I think gulp must be remove to make understandable prepare scripts.
I start rework this part and I will soon PR this issue.

**Comment by samuel-gomez-axa** [comment]
Can you explain alternative solution you want to use, please ?

FYI, the last version 1.1.2, remove the partial SASS import.

**Comment by arnaudforaison** [comment]
My refactor is focus on remove usage of gulp with npm scripts.
First I will focus on gulp prepare command

**Comment by gcruchon** [comment]
Hi all, is this bug still relevant now that we have scripts ?

**Comment by samuel-gomez-axa** [comment]
yes, i think we can close
