### ISSUE TITLE
Npm 7 et les versions de React

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-toolkit#850]
Hello

Je suis passé sur Npm7 et j'ai voulu faire un npm install sur mon projet.

https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

Et ça pète un peu de partout sur la gestion des versions

![image](https://user-images.githubusercontent.com/40664502/107645773-6e29ae00-6c79-11eb-8542-44c31f1e6408.png)

**Comment by arnaudforaison** [comment]
Est ce que tu constates le problème de React 17 sur la version latest (1.4.0-alpha2) ? Car @xballoy avait fait cette PR #798 
Je regarde pour npm 7

**Comment by jforatier** [comment]
J'ai fait face à des problématiques aussi => Issue #841

**Comment by arnaudforaison** [comment]
En complément, je me posais la question si Lerna avait fait le nécessaire.
Il est parti en burnout - https://github.com/lerna/lerna/issues/2703#issuecomment-744601134

mais il semble qu'une nouvelle version (il y a 2 jours) arrive
https://github.com/lerna/lerna/issues/2703#issuecomment-777089520

**Comment by xballoy** [comment]
A tester mais quand tu vois le changelog de la version 4.0.0 ça ne va pas changer grand chose...

**Comment by xballoy** [comment]
A voir si on a toujours besoin de lerna comme on publie toujours tous les composants ¯\_(ツ)_/¯

**Comment by arnaudforaison** [comment]
Encore plus avec les changements de cette version 7 de npm:
- Workspaces https://dev.to/limal/simplify-your-monorepo-with-npm-7-workspaces-5gmj
- yarn.lock compatibilité

**Comment by jforatier** [comment]
J'arrive sûrement après la bataille mais lerna m'a pas fait une belle impression. Ok la lib fait de belle promesse en standalone mais le coût d'appropriation dans un sujet type tooling est énorme. Ça peut décourager.
