### ISSUE TITLE
Découpage des stories du storybook

### ISSUE THREAD

**Issue by arnaudforaison** [AxaGuilDEv/react-toolkit#864]
Le découpage actuel des stories est difficile à comprendre sur plusieurs points :
- on ne sait pas trop ce à quoi correspondent les composants Core voir nommé Base des fois
- Pas facile de naviguer entre Form (et ses sous composants) Layout. En gros difficile de s'y repéré
- Toutes les stories n'utilisent pas les controls et les controls doivent être au format des props du composant

Mon idée serait de créer les composants de plus haut niveau dans un dossier storybook à plat et les composants de base doivent soit avoir un autre dossier storybook soit être documenté dans leur readme. 

Vos avis ? @johnmeunier @jforatier @xballoy @samuel-gomez @youf-olivier et les autres

**Comment by JLou** [comment]
Est-ce qu'il ne serait pas plus simple pour démarrer, de juste documenter les composants. Pour avoir fait monter en compétence plusieurs personnes sur le toolkit, le storybook n'est pas facile a comprendre (en l'état) pour quelqu'un qui ne connait pas bien react.
Du coté suisse, ils ont produit ça : https://patterns.axa.ch/?path=/story/components-input-text--input-text
Avec l'onglet usage + les knobs ca devient plus facile de comprendre l'usage, je trouve.

**Comment by romuleald** [comment]
La guilde UX devrait pouvoir fournir la logique des composants, c'est eux qui définissent la notion d'atome, molécule etc.
Le regroupement des éléments de formulaire pourrait être en effet une bonne chose.

**Comment by arnaudforaison** [comment]
@JLou je pense que [Storybook Docs](https://storybook.js.org/docs/react/writing-docs/introduction) répond à ta demande. Qu'est ce que tu en penses ?
Dans ce cas il faut revoir quel composant on met dans le storybook (base/core ou les inputs ou l'autres) et écrire les stories en conséquence (surtout la partie doc)

**Comment by samuel-gomez-axa** [comment]
Il y a plusieurs manques sur le storybook : 

- composants de plus haut niveau (je rejoins @arnaudforaison sur ce point) qui répondent à la majeure partie des besoins et rappeler que les composants bas niveau ne sont à utiliser que pour les besoins spécifiques.
- Trouver une même règle de nommage pour le 'niveau' du composant 'core', 'raw' ou 'base' et uniformiser tous les composants.
- Réorganiser les composants pour meilleure lisibilité
- les storysources ne sont pas très lisibles car toutes les stories du composant sont regroupées.
- Améliorer la doc, peu importe le format (on a le Readme mais on peut mettre Storybook Docs)
- Plus d'exemples d'utilisation

Je pense que ça nécessite un atelier, qu'en pensez-vous ?

**Comment by JLou** [comment]
> @JLou je pense que [Storybook Docs](https://storybook.js.org/docs/react/writing-docs/introduction) répond à ta demande. Qu'est ce que tu en penses ?
> Dans ce cas il faut revoir quel composant on met dans le storybook (base/core ou les inputs ou l'autres) et écrire les stories en conséquence (surtout la partie doc)

Ca a l'air top au premier coup d'oeil ouais !

**Comment by johnmeunier** [comment]
L'un des plus gros problème que l'on a rencontré sur le storybook concerne l'affichage du code des stories elle même. C'est très difficile de lire quelle story correspond à quel composant car elles sont toutes regroupées au même endroit. De plus, avec la volonté d'utiliser les actions, les props à passer pour reproduire la story sont compliqué à comprendre. 

J'aime bien l'affichage très simple du composant rendu suivi du code de la story qui a été écrit pour ce composant en particulier : 

![image](https://user-images.githubusercontent.com/14071674/108733573-e8d2b300-752e-11eb-8650-c8d263d6b23b.png)

**Comment by arnaudforaison** [comment]
Les issues relatives à cette discussion ont été crées
#903 #904 #905 #906 #907 #908 #909
