### ISSUE TITLE
Add data-testid to pager options to be able to test behaviour with react-testing-library

### ISSUE THREAD

**Issue by bernard-arnaud** [AxaGuilDEv/react-toolkit#868]
### Issue and Steps to Reproduce

To be able to test a select option change with react-testing-library, an attribute data-testid must be put on each option.
To improve testing, is it possible to add a data-testid to each option of the Pager component ?

**Comment by arnaudforaison** [comment]
You can test it with [user-event](https://testing-library.com/docs/ecosystem-user-event), not necessary to add a data-testid prop
