### ISSUE TITLE
Failed to compile alert.scss

### ISSUE THREAD

**Issue by triathletefr23** [AxaGuilDEv/react-toolkit#9]
### Issue and Steps to Reproduce

Following the guideline example

### Versions

1.0.0

### Screenshots

![image](https://user-images.githubusercontent.com/9766356/49116171-17547b80-f29d-11e8-98c4-7db2a95914d3.png)

### Additional Details

- Installed packages:
@axa-fr/react-toolkit-alert

**Comment by guillaumechervetaxa** [comment]
Hi @triathletefr23,

Thanks a lot for the reports !
There are bugs on scss. Imports are missing.
@samuel-gomez-axa may fix it very quickly.

You can temporary use the compiled css instead :
@axa-fr/react-toolkit-alert/dist/af-alert.css
