### ISSUE TITLE
Les modifiers des boutons ne sont pas totalement en camelCase

### ISSUE THREAD

**Issue by johnmeunier** [AxaGuilDEv/react-toolkit#900]
Les modifiers du toolkit comme hasiconRight ou hasiconLeft sont censés s'écrire hasIconRight ou encore hasIconLeft. 

Ca peut engendre des breakings changes car une classe est sensible à la casse, il faudrait dans un premier temps supporter les deux classes en même temps. 

A voir également si ces typos ne sont pas présentes ailleurs, sur d'autres composants.

**Comment by DanneelsSophie** [comment]
@johnmeunier  Je vais essayer de regarder pour cette issue !
