### ISSUE TITLE
Include a 3rd state in checkbox, the indeterminate state

### ISSUE THREAD

**Issue by Gounaya** [AxaGuilDEv/react-toolkit#917]
### Issue and Steps to Reproduce
The checkbox has 2 states, Tristate checkbox has true for checked, false for unchecked and null for undeterminate.
To build a tree of checkbox options, we need to include another state.

#### Versions
1.4.0-alpha.0

#### Screenshots
![Sans titre](https://user-images.githubusercontent.com/31968200/115400473-9ee21280-a1e9-11eb-9ab4-b4710e28a466.png)

#### Expected
We already have two states checked and unchecked (true or false), the goal is to include a 3rd state indeterminate is equal to **null**

**Comment by Gounaya** [comment]
I created a component with all three states in our react-components project
https://doc-ose.axa-fr.intraxa/latest/?path=/story/components-tristatecheckbox--tri-state-checkbox-indeterminate

**Comment by guillaume-chervet** [comment]
Please for security do not share internal url.
