### ISSUE TITLE
Slash division in sass is deprecated

### ISSUE THREAD

**Issue by JLou** [AxaGuilDEv/react-toolkit#922]
### Issue and Steps to Reproduce

Division using / are deprecated and going to be removed in dart sass 2.0.0

When you build an app with sass 1.35.1, you get a warning saying : "DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0."

This issue appears mainly with the file @axa-fr\react-toolkit-core\src\common\scss\_variables.scss

#### Versions

1.4.0

#### Screenshots

![image](https://user-images.githubusercontent.com/183460/123076964-e8cdbb80-d419-11eb-97b7-f8dfe4e959b6.png)

#### Additional Details

there is a tool to automate the change here : https://sass-lang.com/documentation/breaking-changes/slash-div
- Installed packages
@axa-fr\react-toolkit-core

**Comment by samuel-gomez-axa** [comment]
done for vnext (2.0.0-alpha.4)
