### ISSUE TITLE
Input Select does not work

### ISSUE THREAD

**Issue by rpetigny** [AxaGuilDEv/react-toolkit#968]
### Issue and Steps to Reproduce

This codesandbox illustrates the problem: https://codesandbox.io/s/gifted-elbakyan-dkd87g?file=/src/App.js
Error in console at startup:
« Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. »
And onChange handler never called

#### Versions
2.0.0-alpha.8

#### Expected
onChange correctly working

#### Additional Details
Switch back to alpha.5 and the sample works

- Installed packages

**Comment by bernard-arnaud** [comment]
classModifier is also not properly passed down.

Here's a sandbox to showcase both issues : 
[](https://codesandbox.io/s/condescending-ptolemy-m32ol1)

**Comment by samuel-gomez** [comment]
Fixed on v2.0.0 : https://codesandbox.io/s/select-n3o3b5
